build: false

environment:
  matrix:
    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7.x"
      PYTHON_ARCH: "32"

install:
  - "%PYTHON%/Scripts/pip.exe install networkx"
  - "%PYTHON%/Scripts/pip.exe install matplotlib"

test_script:
  - cd code
  - python seeding.py